development:
    adapter: mysql
    encoding: utf8
    database: test_twt
    username: admin_test_twt
    password: twitter
    host: 70.32.99.240

production:
    adapter: mysql
    encoding: utf8
    database: test_twt
    username: admin_test_twt
    password: twitter
    host: 70.32.99.240
